(function(root){'use strict';const C=root.RISK_CONFIG;
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const yes=v=>v===true?'Yes':v===false?'No':'Unknown';
function table(head,rows){return '<div class="table-wrap"><table><thead><tr>'+head.map(x=>'<th>'+esc(x)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(row=>'<tr>'+row.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';}
function card(r,path){const labels=path?Object.fromEntries(r.nodes.map(n=>[n.id,n.label||C.threats.find(t=>t.id===n.risk)?.name])):{};
 const title=path?r.id:r.name;const chain=path?r.edges.map(([a,rel,b])=>labels[a]+' '+rel.toLowerCase()+' '+labels[b]).join('; '):r.definition;
 let html='<article class="risk-card"><div class="card-head"><h3>'+esc(title)+'</h3><span class="score">'+r.base_score+' <span class="muted">/ 12</span></span></div><div class="badges"><span class="badge '+r.priority.toLowerCase()+'">'+esc(r.priority)+' baseline priority</span><span class="badge '+r.applicability.toLowerCase().replaceAll(' ','-')+'">'+esc(r.applicability)+'</span></div><p>'+esc(chain)+'</p>';
 html+='<p class="muted">'+(r.applicability==='Applicable'?'Reported capabilities support this concern; this is not evidence of an incident.':r.applicability==='Uncertain'?'Some required facts are unknown. Verify them before concluding whether this applies.':'A required capability is absent for this route. The baseline score is shown for reference.')+'</p>';
 if(!path){html+='<p class="muted">Severity: '+esc(r.severity_label)+' · Overall likelihood: '+esc(r.likelihood_label)+'</p>';if(r.severity_note)html+='<p>'+esc(r.severity_note)+' Possible baseline: '+r.base_score+'–'+r.base_score_upper+'.</p>';
 html+='<p class="muted">Workflow: '+esc(Object.entries(r.workflow_mapping).map(([k,v])=>k+': '+v.join(', ')).join('; '))+'</p>';
 if(r.weakness!==null)html+='<p class="muted">Mapped weakness reported: '+yes(r.weakness_value)+'</p>';
 }else{html+='<p>'+esc(r.scenario)+'</p><p class="muted">Workflow: '+esc(r.workflow.join(' → '))+'</p>';if(r.source_note)html+='<p class="muted">Scope: '+esc(r.source_note)+'</p>';if(r.enabling_results.length)html+=table(['Enabling condition','Present'],r.enabling_results.map(e=>[e.condition,yes(e.value)]));}
 html+='<details><summary>Why this result / facts to verify</summary>'+(r.evidence.length?table(['System fact','Answer'],r.evidence.map(e=>[e.question,yes(e.value)])):'<p>This concern is relevant to all assessed agents.</p>')+'</details>';
 if(r.applicability!=='Not applicable'){html+='<h4>Protection methods</h4><ul class="controls-list">'+r.controls.map(c=>'<li><strong>'+esc(c.title)+'</strong> <span class="badge">'+esc(c.state)+'</span><p>'+esc(c.next_action)+'</p><small>'+esc(c.component)+' · '+esc(c.owner)+'</small></li>').join('')+'</ul>';}
 return html+'</article>';}
function group(title,items,path,collapse=false){if(!items.length)return '';const content=items.map(r=>card(r,path)).join('');return collapse?'<details class="group"><summary>'+esc(title)+' ('+items.length+')</summary>'+content+'</details>':'<h3>'+esc(title)+'</h3>'+content;}
function body(r){const all=[...r.independent_risks,...r.risk_propagation_paths],high=r.independent_risks.filter(x=>x.applicability==='Applicable'&&['High','Critical'].includes(x.priority)).length;
 let h='<div class="report"><header class="report-intro"><div class="eyebrow">YOUR ASSESSMENT</div><h1>Agentic AI risk review</h1><p class="muted">Generated '+esc(new Date(r.generated_at).toLocaleString())+' · Framework '+esc(r.schema_version)+'</p></header><div class="report-stats"><div class="stat"><strong>'+high+'</strong><span>Applicable High / Critical risks</span></div><div class="stat"><strong>'+all.filter(x=>x.applicability==='Uncertain').length+'</strong><span>Risks or paths needing clarification</span></div><div class="stat"><strong>'+r.completeness.percent+'%</strong><span>Information completeness</span></div></div><h2>How to read this report</h2><p>'+esc(r.interpretation)+'</p><p class="muted">Base score = severity × overall likelihood. Low: 1–3; Medium: 4–6; High: 7–9; Critical: 10–12. Completeness counts known answers and is not an accuracy estimate. Memory questions are deferred.</p>';
 for(const [title,key,path]of [['Independent risks','independent_risks',false],['Risk propagation paths','risk_propagation_paths',true]]){const xs=r[key];h+='<h2>'+title+'</h2>';const main=xs.filter(x=>x.applicability==='Applicable'&&['High','Critical'].includes(x.priority));h+=main.length?main.map(x=>card(x,path)).join(''):'<p class="empty">No confirmed applicable High or Critical items.</p>';h+=group('Needs clarification',xs.filter(x=>x.applicability==='Uncertain'),path);h+=group('Show Medium and Low items',xs.filter(x=>x.applicability==='Applicable'&&['Medium','Low'].includes(x.priority)),path,true);h+=group('Show items not applicable to this profile',xs.filter(x=>x.applicability==='Not applicable'),path,true);}
 h+='<details><summary>Assessment scope and limitations</summary><ul class="scope-list">'+r.scope_notes.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ul></details>';
 if(r.profile.responses)h+='<details><summary>View your questionnaire answers</summary>'+table(['Question','Answer'],C.survey.filter(q=>Object.hasOwn(r.profile.responses,q.id)).map(q=>{const v=r.profile.responses[q.id];const a=Array.isArray(v)?v:v===null?[]:[v];return [q.title,a.length?a.map(k=>q.options.find(o=>o.id===k)?.label||k).join('; '):'Don’t know / unanswered'];}))+'</details>';
 return h+'</div>';}
const printStyle='body{font:16px/1.6 system-ui,sans-serif;color:#172c3a;max-width:1000px;margin:30px auto;padding:0 24px}h1{font-size:34px}h2{margin-top:36px}.muted,small{color:#586b79}.eyebrow{letter-spacing:.1em;font-size:12px}.report-intro{border-bottom:2px solid #153b50}.report-stats{display:flex;gap:16px;margin:24px 0}.stat{padding:16px;border:1px solid #dce4e9;flex:1}.stat strong{display:block;font-size:26px}.stat span{font-size:14px}.risk-card{border:1px solid #dce4e9;padding:20px;margin:16px 0;border-radius:8px}.card-head{display:flex;justify-content:space-between;gap:15px}.card-head h3{margin:0}.badge{display:inline-block;padding:3px 7px;background:#edf2f5;font-size:12px;margin:5px 4px 5px 0;border-radius:4px}.badges{margin-top:8px}.high,.critical{background:#ffe7db}.uncertain{background:#fff2c9}.controls-list{list-style:none;padding:0}.controls-list li{padding:10px 0;border-bottom:1px solid #dce4e9}.controls-list p{margin:4px 0}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse;font-size:14px}th,td{text-align:left;padding:10px;border-bottom:1px solid #dce4e9;vertical-align:top}summary{cursor:pointer;font-weight:650;padding:12px 0}.group{padding:12px;background:#f4f7f9}details{margin:12px 0}@media(max-width:600px){.report-stats{display:block}}@media print{body{margin:0;padding:0}details>*{display:block!important}}';
function html(r){return '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Agentic AI risk review</title><style>'+printStyle+'</style></head><body>'+body(r)+'</body></html>';}
root.RiskReport={body,html,escape:esc};})(globalThis);
